version: '3'

services:

    app:
        build: .
        container_name: auction-app
        entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
        ports:
          - "6001:6001"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
            - redis
        links:
          - "redis"

    nginx:
        build: .docker/nginx
        container_name: auction-nginx
        restart: always
        tty: true
        ports:
            - "7123:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - app

    db:
        build: ./.docker/mysql
        command: --innodb-use-native-aio=0
        container_name: auction-db
        restart: always
        tty: true
        ports:
            - "33004:3306"
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
            - ./.docker/mysql/sql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            # - MYSQL_USER=root
        networks:
            - app-network
        links:
          - "redis"
    redis:
      container_name: auction-redis
      image: redis:alpine3.12
      networks:
        - app-network
      restart: always
networks:
    app-network:
        driver: bridge
